/* cache for 'de' (generated at 2026-01-11T15:34:29+00:00) -- DO NOT EDIT */
WoltLabLanguage.registerPhrase('wcf.button.delete.confirmMessage', '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{\/if} <span class=\"confirmationObject\">{$objectTitle}<\/span> wirklich löschen?');
WoltLabLanguage.registerPhrase('wcf.clipboard.item.mark', 'Element markieren');
WoltLabLanguage.registerPhrase('wcf.clipboard.item.markAll', 'Alle Elemente markieren');
WoltLabLanguage.registerPhrase('wcf.clipboard.item.unmarkAll', 'Demarkieren');
WoltLabLanguage.registerPhrase('wcf.date.firstDayOfTheWeek', '1');
WoltLabLanguage.registerPhrase('wcf.date.hour', 'Stunde');
WoltLabLanguage.registerPhrase('wcf.date.minute', 'Minute');
WoltLabLanguage.registerPhrase('wcf.date.relative.now', 'Vor einem Moment');
WoltLabLanguage.registerPhrase('wcf.date.datePicker', 'Datumsauswahl');
WoltLabLanguage.registerPhrase('wcf.date.datePicker.hour', 'Stunde');
WoltLabLanguage.registerPhrase('wcf.date.datePicker.minute', 'Minute');
WoltLabLanguage.registerPhrase('wcf.date.datePicker.month', 'Monat');
WoltLabLanguage.registerPhrase('wcf.date.datePicker.nextMonth', 'Nächster Monat');
WoltLabLanguage.registerPhrase('wcf.date.datePicker.previousMonth', 'Vorheriger Monat');
WoltLabLanguage.registerPhrase('wcf.date.datePicker.year', 'Jahr');
WoltLabLanguage.registerPhrase('wcf.date.datePicker.clear', 'Datumsauswahl zurücksetzen');
WoltLabLanguage.registerPhrase('wcf.date.datePicker.time', 'Uhrzeit auswählen');
WoltLabLanguage.registerPhrase('wcf.date.datePicker.time.clear', 'Uhrzeit zurücksetzen');
WoltLabLanguage.registerPhrase('wcf.dialog.button.cancel', 'Abbrechen');
WoltLabLanguage.registerPhrase('wcf.dialog.button.close', 'Dialog schließen');
WoltLabLanguage.registerPhrase('wcf.dialog.button.primary', 'OK');
WoltLabLanguage.registerPhrase('wcf.dialog.button.primary.confirm', 'Bestätigen');
WoltLabLanguage.registerPhrase('wcf.dialog.button.primary.delete', 'Löschen');
WoltLabLanguage.registerPhrase('wcf.dialog.button.primary.restore', 'Wiederherstellen');
WoltLabLanguage.registerPhrase('wcf.dialog.button.primary.submit', 'Absenden');
WoltLabLanguage.registerPhrase('wcf.dialog.confirmation.cannotBeUndone', 'Dieser Vorgang kann nicht rückgängig gemacht werden.');
WoltLabLanguage.registerPhrase('wcf.dialog.confirmation.delete', '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{\/if} „{$title}“ wirklich löschen?');
WoltLabLanguage.registerPhrase('wcf.dialog.confirmation.delete.indeterminate', '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{\/if} dies wirklich löschen?');
WoltLabLanguage.registerPhrase('wcf.dialog.confirmation.softDelete', '{if LANGUAGE_USE_INFORMAL_VARIANT}Möchtest du{else}Möchten Sie{\/if} „{$title}“ in den Papierkorb verschieben?');
WoltLabLanguage.registerPhrase('wcf.dialog.confirmation.softDelete.indeterminate', '{if LANGUAGE_USE_INFORMAL_VARIANT}Möchtest du{else}Möchten Sie{\/if} dies in den Papierkorb verschieben?');
WoltLabLanguage.registerPhrase('wcf.dialog.confirmation.restore', '{if LANGUAGE_USE_INFORMAL_VARIANT}Möchtest du{else}Möchten Sie{\/if} „{$title}“ wiederherstellen?');
WoltLabLanguage.registerPhrase('wcf.dialog.confirmation.restore.indeterminate', '{if LANGUAGE_USE_INFORMAL_VARIANT}Möchtest du{else}Möchten Sie{\/if} dies wiederherstellen?');
WoltLabLanguage.registerPhrase('wcf.dialog.confirmation.reason', 'Grund');
WoltLabLanguage.registerPhrase('wcf.dialog.confirmation.reason.optional', 'Grund (optional)');
WoltLabLanguage.registerPhrase('wcf.global.button.add', 'Hinzufügen');
WoltLabLanguage.registerPhrase('wcf.global.button.cancel', 'Abbrechen');
WoltLabLanguage.registerPhrase('wcf.global.button.close', 'Schließen');
WoltLabLanguage.registerPhrase('wcf.global.button.collapsible', 'Auf- und Zuklappen');
WoltLabLanguage.registerPhrase('wcf.global.button.delete', 'Löschen');
WoltLabLanguage.registerPhrase('wcf.global.button.disable', 'Deaktivieren');
WoltLabLanguage.registerPhrase('wcf.global.button.disabledI18n', 'einsprachig');
WoltLabLanguage.registerPhrase('wcf.global.button.edit', 'Bearbeiten');
WoltLabLanguage.registerPhrase('wcf.global.button.enable', 'Aktivieren');
WoltLabLanguage.registerPhrase('wcf.global.button.hide', 'Ausblenden');
WoltLabLanguage.registerPhrase('wcf.global.button.hideMenu', 'Menü verbergen');
WoltLabLanguage.registerPhrase('wcf.global.button.insert', 'Einfügen');
WoltLabLanguage.registerPhrase('wcf.global.button.markAsRead', 'Als gelesen markieren');
WoltLabLanguage.registerPhrase('wcf.global.button.markAllAsRead', 'Alle als gelesen markieren');
WoltLabLanguage.registerPhrase('wcf.global.button.more', 'Mehr');
WoltLabLanguage.registerPhrase('wcf.global.button.next', 'Weiter »');
WoltLabLanguage.registerPhrase('wcf.global.button.preview', 'Vorschau');
WoltLabLanguage.registerPhrase('wcf.global.button.reset', 'Zurücksetzen');
WoltLabLanguage.registerPhrase('wcf.global.button.rss', 'RSS-Feed');
WoltLabLanguage.registerPhrase('wcf.global.button.save', 'Speichern');
WoltLabLanguage.registerPhrase('wcf.global.button.search', 'Suchen');
WoltLabLanguage.registerPhrase('wcf.global.button.showMenu', 'Menü anzeigen');
WoltLabLanguage.registerPhrase('wcf.global.button.submit', 'Absenden');
WoltLabLanguage.registerPhrase('wcf.global.button.upload', 'Hochladen');
WoltLabLanguage.registerPhrase('wcf.global.button.replace', 'Ersetzen');
WoltLabLanguage.registerPhrase('wcf.global.confirmation.cancel', 'Abbrechen');
WoltLabLanguage.registerPhrase('wcf.global.confirmation.confirm', 'OK');
WoltLabLanguage.registerPhrase('wcf.global.confirmation.title', 'Bestätigung erforderlich');
WoltLabLanguage.registerPhrase('wcf.global.error.ajax.network', '<p>Ein Verbindungsaufbau zum Server war nicht möglich, bitte überprüfen Sie Ihre Internetverbindung.<\/p><p><br><\/p><p>Fehlermeldung von Ihrem Browser: „{$message}“<\/p>');
WoltLabLanguage.registerPhrase('wcf.global.error.timeout', 'Keine Antwort vom Server erhalten, Anfrage wurde abgebrochen.');
WoltLabLanguage.registerPhrase('wcf.global.error.title', 'Fehlermeldung');
WoltLabLanguage.registerPhrase('wcf.global.form.error.empty', 'Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}fülle{else}füllen Sie{\/if} dieses Eingabefeld aus.');
WoltLabLanguage.registerPhrase('wcf.global.form.error.greaterThan', 'Der eingegebene Wert muss größer sein als {#$greaterThan}.');
WoltLabLanguage.registerPhrase('wcf.global.form.error.lessThan', 'Der eingegebene Wert muss kleiner sein als {#$lessThan}.');
WoltLabLanguage.registerPhrase('wcf.global.form.input.maxItems', 'Maximale Anzahl erreicht');
WoltLabLanguage.registerPhrase('wcf.global.form.error.multilingual', 'Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}fülle{else}füllen Sie{\/if} dieses Eingabefeld für jede Sprache aus.');
WoltLabLanguage.registerPhrase('wcf.global.form.password.button.hide', 'Kennwort verbergen');
WoltLabLanguage.registerPhrase('wcf.global.form.password.button.show', 'Kennwort anzeigen');
WoltLabLanguage.registerPhrase('wcf.global.language.noSelection', 'Keine Auswahl');
WoltLabLanguage.registerPhrase('wcf.global.loading', 'Lädt …');
WoltLabLanguage.registerPhrase('wcf.global.noSelection', '(Keine Auswahl)');
WoltLabLanguage.registerPhrase('wcf.global.page.next', 'Nächste Seite');
WoltLabLanguage.registerPhrase('wcf.global.page.pagination', 'Navigation');
WoltLabLanguage.registerPhrase('wcf.global.page.previous', 'Vorherige Seite');
WoltLabLanguage.registerPhrase('wcf.global.reason', 'Begründung');
WoltLabLanguage.registerPhrase('wcf.global.reason.optional', 'Begründung (optional)');
WoltLabLanguage.registerPhrase('wcf.global.scrollUp', 'Zum Seitenanfang');
WoltLabLanguage.registerPhrase('wcf.global.select', 'Auswählen');
WoltLabLanguage.registerPhrase('wcf.global.success', 'Die Aktion wurde erfolgreich ausgeführt.');
WoltLabLanguage.registerPhrase('wcf.global.success.add', 'Der Eintrag wurde gespeichert.');
WoltLabLanguage.registerPhrase('wcf.global.success.edit', 'Die Änderungen wurden gespeichert.');
WoltLabLanguage.registerPhrase('wcf.global.rss.accessToken.info', 'Der Link zum anonymen RSS-Feed enthält nur Inhalte, auf die Gäste Zugriff haben. Der Link zum personalisierten RSS-Feed enthält alle Inhalte, auf die {if LANGUAGE_USE_INFORMAL_VARIANT}du{else}Sie{\/if} Zugriff {if LANGUAGE_USE_INFORMAL_VARIANT}hast{else}haben{\/if}.');
WoltLabLanguage.registerPhrase('wcf.global.rss.copy', 'Link kopieren');
WoltLabLanguage.registerPhrase('wcf.global.rss.copy.success', 'Der Link wurde erfolgreich kopiert.');
WoltLabLanguage.registerPhrase('wcf.global.rss.withoutAccessToken', 'Anonymer RSS-Feed');
WoltLabLanguage.registerPhrase('wcf.global.rss.withAccessToken', 'Personalisierter RSS-Feed');
WoltLabLanguage.registerPhrase('wcf.like.button.dislike', 'Gefällt mir nicht');
WoltLabLanguage.registerPhrase('wcf.like.button.like', 'Gefällt mir');
WoltLabLanguage.registerPhrase('wcf.like.details', 'Details');
WoltLabLanguage.registerPhrase('wcf.like.summary', '{literal}{if $others == 0}{@$users.slice(0, -1).join(\", \")}{if $users.length > 1} und {\/if}{@$users.slice(-1)[0]}{else}{@$users.join(\", \")} und {if $others == 1}einem{else}{#$others}{\/if} weiteren{\/if} gefällt das.{\/literal}');
WoltLabLanguage.registerPhrase('wcf.like.tooltip', '{if $likes}{#$likes} Like{if $likes != 1}s{\/if}{if $dislikes}, {\/if}{\/if}{if $dislikes}{#$dislikes} Dislike{if $dislikes != 1}s{\/if}{\/if}');
WoltLabLanguage.registerPhrase('wcf.menu.page', 'Menü');
WoltLabLanguage.registerPhrase('wcf.menu.page.button.toggle', 'Weitere {$title} Seiten');
WoltLabLanguage.registerPhrase('wcf.menu.user', 'Benutzer-Menü');
WoltLabLanguage.registerPhrase('wcf.message.share', 'Teilen');
WoltLabLanguage.registerPhrase('wcf.message.share.copy', 'Code kopieren');
WoltLabLanguage.registerPhrase('wcf.message.share.copy.success', 'Der Code wurde erfolgreich kopiert.');
WoltLabLanguage.registerPhrase('wcf.message.share.nativeShare', 'Weitere Optionen');
WoltLabLanguage.registerPhrase('wcf.message.share.permalink', 'Permalink');
WoltLabLanguage.registerPhrase('wcf.message.share.permalink.bbcode', 'BBCode');
WoltLabLanguage.registerPhrase('wcf.message.share.permalink.html', 'HTML');
WoltLabLanguage.registerPhrase('wcf.message.share.socialMedia', 'Social Media');
WoltLabLanguage.registerPhrase('wcf.moderation.report.reportContent', 'Inhalt melden');
WoltLabLanguage.registerPhrase('wcf.page.jumpTo', 'Gehe zu Seite');
WoltLabLanguage.registerPhrase('wcf.page.jumpTo.description', '{if LANGUAGE_USE_INFORMAL_VARIANT}Gib{else}Geben Sie{\/if} einen Wert zwischen „1“ und „{$pages}“ ein.');
WoltLabLanguage.registerPhrase('wcf.page.jumpTo.pageNo', 'Seitenzahl');
WoltLabLanguage.registerPhrase('wcf.page.pageNo', 'Seite {#$pageNo}');
WoltLabLanguage.registerPhrase('wcf.page.pagePosition', 'Seite {#$pageNo} von {#$pages}');
WoltLabLanguage.registerPhrase('wcf.page.pagination', 'Seiten-Navigation');
WoltLabLanguage.registerPhrase('wcf.reactions.react', 'Reagieren');
WoltLabLanguage.registerPhrase('wcf.reactions.summary.listReactions', 'Reaktionen auflisten');
WoltLabLanguage.registerPhrase('wcf.style.changeStyle', 'Stil ändern');
WoltLabLanguage.registerPhrase('wcf.upload.error.damagedImageFile', 'Die Grafikdatei „{$filename}“ ist beschädigt.');
WoltLabLanguage.registerPhrase('wcf.upload.error.emptyFile', 'Die Datei „{$filename}“ ist leer.');
WoltLabLanguage.registerPhrase('wcf.upload.error.fileExtensionNotPermitted', 'Der Dateityp von „{$filename}“ ist unzulässig.');
WoltLabLanguage.registerPhrase('wcf.upload.error.fileSizeTooLarge', 'Die Datei ist zu groß.');
WoltLabLanguage.registerPhrase('wcf.upload.error.maximumCountReached', 'Es {plural value=$maximumCount 1=\'darf nur eine Datei\' other=\'dürfen nur # Dateien\'} hochgeladen werden.');
WoltLabLanguage.registerPhrase('wcf.upload.error.delete.permissionDenied', 'Die Datei kann nicht gelöscht werden, {if LANGUAGE_USE_INFORMAL_VARIANT}verwende{else}verwenden Sie{\/if} stattdessen <strong>Ersetzen<\/strong>, um die Datei zu ersetzen.');
WoltLabLanguage.registerPhrase('wcf.upload.error.delete.unknownError', 'Beim Löschen der Datei ist ein unbekannter Fehler aufgetreten.');
WoltLabLanguage.registerPhrase('wcf.upload.validation.error.noImage', 'Die Datei ist kein Bild.');
WoltLabLanguage.registerPhrase('wcf.upload.validation.error.tooSmall', 'Die Datei ist zu klein.');
WoltLabLanguage.registerPhrase('wcf.user.activityPoint', 'Punkte');
WoltLabLanguage.registerPhrase('wcf.user.language', 'Sprache');
WoltLabLanguage.registerPhrase('wcf.user.panel.settings', 'Einstellungen');
WoltLabLanguage.registerPhrase('wcf.user.panel.showAll', 'Alle anzeigen');
WoltLabLanguage.registerPhrase('wcf.user.button.follow', 'Folgen');
WoltLabLanguage.registerPhrase('wcf.user.button.unfollow', 'Entfolgen');
WoltLabLanguage.registerPhrase('wcf.user.button.ignore', 'Blockieren');
WoltLabLanguage.registerPhrase('wcf.user.button.unignore', 'Nicht mehr blockieren');
/* EOF */
